int _putchar(char);
char *_strcat(char *, char *);
char *_strncat(char *, char *, int);
int _strcmp(char *, char *);
char *_strncpy(char *, char *, int);
void reverse_array(int *a, int n);
char *string_toupper(char *);
char *cap_string(char *);
char *leet(char *);
char *rot13(char *);
void print_number(int n);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
